### ISSUE TITLE
#20 broke some things

### ISSUE THREAD

**Issue by pavelzw** [conda-forge/manimpango-feedstock#21]
### Comment:

#20 removed the `linux-aarch64` support that I added in #18. Also, it added some dependencies [twice](https://github.com/conda-forge/manimpango-feedstock/blob/c9267124b47b0f55af0a0b79241d2cb34b28cf96/recipe/meta.yaml#L20-L26). 

I am not sure why the OSX Arm migrator was triggered here since the `osx-arm64` builds were already there manually.

**Comment by pavelzw** [comment]
@ocefpaf could you maybe revert these changes made in order to support `linux-aarch64` again?

**Comment by ocefpaf** [comment]
> @ocefpaf could you maybe revert these changes made in order to support `linux-aarch64` again?

Those should not be affected by a re-render. I'm looking into what happened.

**Comment by ocefpaf** [comment]
Should be fixed in #22. I'll pay more attention in the next bot PR. Thanks for the warning @pavelzw!
